version: '3.8'
services:
  sonarqube-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/data
    environment:
      - SONAR_HOST_URL=http://localhost:9000
      - SONAR_TOKEN=sqp_bf37b2af42713881e58ae662c7e002a8b0ce75fb
      - SONAR_PROJECT_KEY:"sqp_bf37b2af42713881e58ae662c7e002a8b0ce75f"
      - SONAR_PROJECT_NAME:"Api Testing Tool"
    network_mode: host
