version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    container_name: redis_db
    #restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
